name: Update productive gist

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-gist:
    if: ${{ vars.PINNED_GISTS_ENABLED == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Update productive gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.PINNED_GIST_TOKEN }}
          GIST_ID: ${{ secrets.PRODUCTIVE_GIST_ID }}
          TIMEZONE: Asia/Seoul
